#!/bin/bash

set -e

# Usuario que se puede usar para copiar los archivos mediante scp
SCP_USER=
PG_PORT=
DBNAME=
TOKEN=
BASE_BACKUP_FOLDER=
BASE_MEDIA_FOLDER=
WEB_PORT=
WEB_URL=
export PGPASSWORD=

# Remove old backups
BACKUP_FOLDER=${BASE_BACKUP_FOLDER}/sirha_${DBNAME}/backups
rm -rf ${BACKUP_FOLDER}
mkdir -p ${BACKUP_FOLDER}

pg_dump -h localhost -p ${PG_PORT} -U postgres -Fc -Z9 -E UTF-8 -f ${BACKUP_FOLDER}/${DBNAME}_bck_$(date +%y%m%d).dump ${DBNAME} 2> ${BACKUP_FOLDER}/pgdump.log
tar czf ${BACKUP_FOLDER}/${DBNAME}_files_bck_$(date +%y%m%d).tgz ${BASE_MEDIA_FOLDER}/media 2> ${BACKUP_FOLDER}/tar_files.log

curl "${WEB_URL}:${WEB_PORT}/api/nuevo_ciclo_facturacion?token_new_fact_cycle=${TOKEN}" > ${BACKUP_FOLDER}/nuevo_ciclo_facturacion.log 2>&1

chown -R ${SCP_USER}:${SCP_USER} ${BACKUP_FOLDER}
