-- Deploy utentes:basic_gis_permissions to pg

BEGIN;

-- CREATE ROLE "sirha_base_user" WITH NOSUPERUSER NOCREATEDB NOCREATEROLE INHERIT NOLOGIN NOREPLICATION;
-- CREATE USER "tecnico" WITH NOSUPERUSER NOCREATEDB NOCREATEROLE INHERIT LOGIN NOREPLICATION PASSWORD 'tecnico1905';
-- GRANT "sirha_base_user" TO "tecnico";

REVOKE ALL ON ALL TABLES IN SCHEMA public FROM PUBLIC;
REVOKE ALL ON ALL TABLES IN SCHEMA cbase FROM PUBLIC;
REVOKE ALL ON ALL TABLES IN SCHEMA cbase_ara FROM PUBLIC;
REVOKE ALL ON ALL TABLES IN SCHEMA domains FROM PUBLIC;
REVOKE ALL ON ALL TABLES IN SCHEMA elle FROM PUBLIC;
REVOKE ALL ON ALL TABLES IN SCHEMA inventario FROM PUBLIC;
REVOKE ALL ON ALL TABLES IN SCHEMA inventario_dominios FROM PUBLIC;
REVOKE ALL ON ALL TABLES IN SCHEMA sqitch FROM PUBLIC;
REVOKE ALL ON ALL TABLES IN SCHEMA utentes FROM PUBLIC;

REVOKE ALL ON ALL SEQUENCES IN SCHEMA public FROM PUBLIC;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA cbase FROM PUBLIC;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA cbase_ara FROM PUBLIC;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA domains FROM PUBLIC;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA elle FROM PUBLIC;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA inventario FROM PUBLIC;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA inventario_dominios FROM PUBLIC;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA sqitch FROM PUBLIC;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA utentes FROM PUBLIC;

REVOKE ALL ON SCHEMA public FROM PUBLIC;
REVOKE ALL ON SCHEMA cbase FROM PUBLIC;
REVOKE ALL ON SCHEMA cbase_ara FROM PUBLIC;
REVOKE ALL ON SCHEMA domains FROM PUBLIC;
REVOKE ALL ON SCHEMA elle FROM PUBLIC;
REVOKE ALL ON SCHEMA inventario FROM PUBLIC;
REVOKE ALL ON SCHEMA inventario_dominios FROM PUBLIC;
REVOKE ALL ON SCHEMA sqitch FROM PUBLIC;
REVOKE ALL ON SCHEMA utentes FROM PUBLIC;

GRANT USAGE ON SCHEMA public TO sirha_base_user;
GRANT USAGE ON SCHEMA cbase TO sirha_base_user;
GRANT USAGE ON SCHEMA cbase_ara TO sirha_base_user;
GRANT USAGE ON SCHEMA domains TO sirha_base_user;
GRANT USAGE ON SCHEMA elle TO sirha_base_user;
GRANT USAGE ON SCHEMA inventario TO sirha_base_user;
GRANT USAGE ON SCHEMA inventario_dominios TO sirha_base_user;
GRANT USAGE ON SCHEMA utentes TO sirha_base_user;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA inventario TO sirha_base_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA utentes TO sirha_base_user;
GRANT USAGE ON ALL SEQUENCES IN SCHEMA inventario TO sirha_base_user;
GRANT USAGE ON ALL SEQUENCES IN SCHEMA utentes TO sirha_base_user;

GRANT SELECT ON ALL TABLES IN SCHEMA public TO sirha_base_user;
GRANT SELECT ON ALL TABLES IN SCHEMA cbase TO sirha_base_user;
GRANT SELECT ON ALL TABLES IN SCHEMA cbase_ara TO sirha_base_user;
GRANT SELECT ON ALL TABLES IN SCHEMA domains TO sirha_base_user;
GRANT SELECT ON ALL TABLES IN SCHEMA elle TO sirha_base_user;
GRANT SELECT ON ALL TABLES IN SCHEMA inventario_dominios TO sirha_base_user;



COMMIT;
