-- Deploy sixhiara:create_roles_inventario to pg

BEGIN;

CREATE ROLE inventario_read WITH NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOLOGIN NOREPLICATION;
CREATE ROLE inventario_write WITH NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOLOGIN NOREPLICATION;

COMMIT;
