-- Deploy utentes:create_tables_cbase_unidades to pg

BEGIN;

ALTER TABLE cbase.bacias ADD COLUMN unidade TEXT;
ALTER TABLE cbase_ara.bacias ADD COLUMN unidade TEXT;

CREATE TABLE cbase.unidades (
    gid int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome TEXT,
    siglas TEXT,
    ara TEXT,
    area NUMERIC(10, 2),
    bacia_prin TEXT,
    rio_prin TEXT,
    geom GEOMETRY(MULTIPOLYGON, 32737)
);
CREATE INDEX ON cbase.unidades USING GIST (geom);
REVOKE ALL ON TABLE cbase.unidades FROM PUBLIC;
GRANT SELECT ON TABLE cbase.unidades TO :base_user;




CREATE TABLE cbase_ara.unidades (
    gid int PRIMARY KEY REFERENCES cbase.unidades(gid) ON UPDATE CASCADE ON DELETE CASCADE,
    nome TEXT,
    siglas TEXT,
    ara TEXT,
    area NUMERIC(10, 2),
    bacia_prin TEXT,
    rio_prin TEXT,
    geom GEOMETRY(MULTIPOLYGON, 32737)
);
CREATE INDEX ON cbase_ara.unidades USING GIST (geom);
REVOKE ALL ON TABLE cbase.unidades FROM PUBLIC;
GRANT SELECT ON TABLE cbase.unidades TO :base_user;

COMMIT;
